### ISSUE TITLE
About blur 

### ISSUE THREAD

**Issue by RodenLuo** [preddy5/DiffCompositing#4]
Hi,

Great work and thanks very much for releasing the code! 

If I am not mistaken, the following code is for section 5, subsection "Multi-resolution pyramid.", page 6 of the paper. 

https://github.com/preddy5/DiffCompositing/blob/7cd534e2518feb8b0ebb01e58ced42abe8a22e79/DC/sampling.py#L64

But, shouldn't the two `img` be `img_bg` so that the blur is taking its effect, as two lines after, it is `img_bg` being used? 

Thanks

**Comment by preddy5** [comment]
Hey @RodenLuo 
Sorry for the late reply.
No that blur is so that we extend the spatial extent of the gradients from grid_sample for each pattern element.
If you are looking for multi-resolution pyramid code you could use this function https://github.com/preddy5/Im2Vec/blob/f6516e0938b6101aacda893be6cfc668cf82f5f8/models/vector_vae.py#L357

Regards,

**Comment by RodenLuo** [comment]
Hi Pradyumna, 

Thanks very much! I still didn't get the blur part. But will look into it accordingly with more details. The multi-resolution pyramid now makes much more sense! 

Very best
